- name: Set results directory
  ansible.builtin.set_fact:
    foldername: "{{ lookup('pipe', 'date +%Y-%-m-%-d_%H-%M-%S') }}"

- name: Set toolkit directory
  ansible.builtin.set_fact:
    toolkit_dir: "{{ playbook_dir }}/deployment"
    tests_dir: "{{ playbook_dir }}/benchmark"

#TODO: check this for redundancy
- name: Create results directory
  ansible.builtin.file:
    path: "/tmp/benchfaster/_results/{{ foldername }}"
    state: directory
  register: results_path