---
# tasks file for roles/benchmark/stop
- name: Remove ansible logs from current dir
  ansible.builtin.file:
    path: "{{ playbook_dir }}/ansible.log"
    state: absent
  delegate_to: localhost

- name: Remove results directory from testers
  ansible.builtin.file:
    path: "/tmp/benchfaster/_results/{{ hostvars[groups['testers'][0]]['foldername'] }}"
    state: absent
  register: results_path

- name: Delete /tmp/benchfaster directory from headnode
  file:
    path: /tmp/benchfaster
    state: absent
  delegate_to: "{{ groups['headnodes'][0] }}"
