---
# tasks file for roles/benchfaster/registry-add
- name: Create k3s folder on all machines
  file:
    path: /etc/rancher/k3s
    state: directory
  become: yes
  delegate_to: "{{ hitem }}"
  loop: "{{ groups['all'] }}"
  loop_control:
    loop_var: hitem

- name: Add local container registry to all machines
  ansible.builtin.shell: |
    sudo sed -i '/{{ registry.dname }}/d' /etc/hosts
    cat << EOF | sudo tee /etc/rancher/k3s/registries.yaml > /dev/null
    mirrors:
      {{ registry.dname }}:{{ registry.port }}:
        endpoint:
          - http://{{ registry.dname }}:{{ registry.port }}
    EOF
    echo '{{ registry.ip }} {{ registry.dname }}' | tee -a /etc/hosts
    systemctl restart k3s*
  become: yes
  delegate_to: "{{ hitem }}"
  loop: "{{ groups['all'] }}"
  loop_control:
    loop_var: hitem
  ignore_errors: yes
