# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative 'environment.rb'
include Variables


ENV['VAGRANT_NO_PARALLEL'] = 'yes'
Vagrant.configure("2") do |config|

  config.vm.define "headnode", primary: true do |headnode|
    headnode.vm.box = $VM_IMAGE
    headnode.vm.hostname = "headnode"
    headnode.vm.network "public_network", bridge: $INTERFACE, dev: $INTERFACE, ip: $ADDRESS_BENCHMARK
    headnode.vm.synced_folder "../../..", "/vagrant", type: "nfs", nfs_udp: false
    headnode.vm.provider $VAGRANT_PROVIDER do |hn|
      hn.memory = "#{$VM_MEM}"
      hn.cpus = "#{$VM_CPU}"
    end
    headnode.vm.provision :shell, inline: "DEBIAN_FRONTEND=noninteractive apt update"
    headnode.vm.provision :shell, inline: "echo 'set bell-style none' >> /etc/inputrc && echo 'set visualbell' >> /home/vagrant/.vimrc"
  end

  (1..$NUM_WORKERS).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.box = $VM_IMAGE
      worker.vm.hostname = "worker#{i}"
      worker.vm.network "public_network", bridge: $INTERFACE, dev: $INTERFACE, use_dhcp_assigned_default_route: true
      worker.vm.synced_folder "../../..", "/vagrant", type: "nfs", nfs_udp: false
      worker.vm.provider $VAGRANT_PROVIDER do |wn|
        wn.memory = "#{$VM_MEM}"
        wn.cpus = "#{$VM_CPU}"
      end
      worker.vm.provision :shell, inline: "DEBIAN_FRONTEND=noninteractive apt update"
      worker.vm.provision :shell, inline: "echo 'set bell-style none' >> /etc/inputrc && echo 'set visualbell' >> /home/vagrant/.vimrc"
    end
  end

  config.vm.provision :shell, inline: "DEBIAN_FRONTEND=noninteractive apt-get install -y kitty-terminfo"
end
