---
# tasks file for roles/applications/knative/knative-main
- name: Copy files folder to headnode
  copy:
    src: "files/"
    dest: /tmp/benchfaster/
  delegate_to: "{{ current_host }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: current_host

- name: Install Knative
  ansible.builtin.script: "install.sh \
      machine \
      {{ knative.version }} \
      {{ address_benchmark }} \
      {{ registry.dname }} \
      {{ registry.port }}"
  become: yes
  delegate_to: "{{ groups['headnodes'][0] }}"