- name: Hello-world test
  hosts: testers
  tasks:
    - name: Initialize BenchFaster
      ansible.builtin.include_tasks: "deployment_toolkit/init.yml"

    - name: Set global vars
      ansible.builtin.set_fact:
        headnode: "{{ hostvars[groups.machines[0]] }}" 

    - name: Deploy Nebula network
      ansible.builtin.include_tasks: "{{ toolkit_dir }}/nebula/nebula_network.yml"
      when: hvm is not defined

    - name: Deploy K3s cluster
      ansible.builtin.include_tasks: "{{ toolkit_dir }}/k3s/k3s_cluster.yml"
      when: hvm is not defined
      
    - name: Install OpenFaas on headnode
      ansible.builtin.include_tasks: "{{ toolkit_dir }}/openfaas/openfaas_install.yml"
      when: hvm is not defined

    - name: Apply QoS to all nodes
      ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/qos_intra.yml"
      when: hvm is not defined

    - name: Deploy BenchFaster in hypervisor 
      ansible.builtin.include_tasks: "{{ toolkit_dir }}/hvm.yml"
      when: hvm is defined
    
    - name: Run helloworld test with JMeter
      ansible.builtin.shell: |
        jmeter -n -t {{ playbook_dir }}/performance_tests/helloworld/helloworld_test.jmx \ 
          -Jrequest.ip={{ address_benchmark }} \
          -Jrequest.port={{ openfaas.openfaas_port }} \
          -Jtest.iterations=100 \
          -l {{ results_path.path }}/results_jmeter.csv

    - name: Run helloworld test with K6
      ansible.builtin.shell: |
        k6 run {{ playbook_dir }}/performance_tests/helloworld/helloworld_test.js \
          -e HOST={{ address_benchmark }} \
          -e PORT={{ openfaas.openfaas_port }} \
          --iterations 100 \
          -o csv={{ results_path.path }}/results_k6.csv

