- name: Hello-world test
  hosts: testers
  tasks:
    - name: Set global vars
      ansible.builtin.set_fact:
        date: "{{ lookup('pipe', 'date +%-d-%-m-%Y_%H-%M-%S') }}"
        toolkit_dir: "{{ playbook_dir }}/deployment_toolkit"
        headnode: "{{ hostvars[groups.machines[0]] }}" 

    - name: Create results directory
      ansible.builtin.file:
        path: "{{ playbook_dir }}/_results/{{ date }}"
        state: directory
      register: results_path

# - name: Install machine requirements
#   ansible.builtin.import_playbook: "requirements/machine.yml"

- name: Install tester requirements
  ansible.builtin.import_playbook: "requirements/tester.yml"

- name: Deploy BenchFaster
  ansible.builtin.import_playbook: "deployment_toolkit/main.yml"
  vars:
    headnode: "{{ hostvars.headnode }}"

- name: Run helloworld benchmark  
  ansible.builtin.import_playbook: "performance_tests/helloworld/helloworld_test.yml"

