- name: Hello-world playbook example for knative and jmeter
  hosts: testers
  vars:
    num_iterations: 10
    jmeter_file: hello-world
    function: 
      name: hello-world
      url: "hello-world.default.{{ address_benchmark }}.nip.io"
      port: 80
      path: /
  
  tasks:
    - ansible.builtin.include_role: 
        name: benchfaster/init

    - name: Launch knative/jmeter workflow
      ansible.builtin.import_tasks: workflows/knative_jmeter.yml
    
    - ansible.builtin.include_role: 
        name: benchfaster/finish
