- name: Hello-world playbook example for knative and jmeter
  hosts: testers
  vars:
    application: knative
    benchmark_tool: jmeter
    jmeter: 
      url: "hello-world.functions.{{ address_benchmark }}.nip.io"
      port: 80
      path: /
      file: hello-world.jmx
      iterations: 10
    function: 
      name: hello-world

  tasks:
    - ansible.builtin.include_role: 
        name: benchfaster/init

    - name: Launch knative/jmeter workflow
      ansible.builtin.import_tasks: workflows/knative_simple.yml
    
    - ansible.builtin.include_role: 
        name: benchfaster/finish
