- name: Hello-world playbook example with WAN emulation for knative and jmeter
  hosts: testers
  vars:
    application: knative
    benchmark_tool: jmeter
    jmeter: 
      url: "hello-world.functions.{{ address_benchmark }}.nip.io"
      port: 80
      path: /
      file: hello-world.jmx
      iterations: 10
    function: 
      name: hello-world
    network_sets:
      intra:
        name: [0-int, 1-int]
        delay: [0, 20]
        variance: [0, 2]
        loss: [0, 0.1]
      tm:
        name: [0-tm, 1-tm]
        delay: [0, 20]
        variance: [0, 2]
        loss: [0, 0.1]
  
  tasks:
    - ansible.builtin.include_role: 
        name: benchfaster/init

    - name: Launch knative/jmeter workflow
      ansible.builtin.include_tasks: workflows/knative_simple.yml
      with_together:
        - "{{ network_sets.intra.name }}"
        - "{{ network_sets.intra.delay }}"
        - "{{ network_sets.intra.variance }}"
        - "{{ network_sets.intra.loss }}"
        - "{{ network_sets.tm.name }}"
        - "{{ network_sets.tm.delay }}"
        - "{{ network_sets.tm.variance }}"
        - "{{ network_sets.tm.loss }}"
      loop_control:
        loop_var: net_item
    
    - ansible.builtin.include_role: 
        name: benchfaster/finish
