- name: Hello-world playbook example for openfaas and k6
  hosts: testers
  vars:
    application: openfaas
    benchmark_tool: k6
    k6: 
      url: "{{ address_benchmark }}"
      port: 31112
      path: /function/hello-world
      file: hello-world.js
      iterations: 10
    function: 
      name: hello-world
    registry: 
      user: ubuntu
      ip: 134.169.115.71
      port: 5000
      dname: local-registry
      
  tasks:
    - ansible.builtin.include_role: 
        name: benchfaster/init

    - name: Launch openfaas/k6 workflow
      ansible.builtin.import_tasks: workflows/generic_simple.yml
    
    - ansible.builtin.include_role: 
        name: benchfaster/finish