- name: Deploy local container registry
  hosts: testers
  vars:
    reg_user: ubuntu
    reg_ip: 192.168.1.247
    reg_port: 5000
    reg_dname: local-registry
    container_images:
      - michalkeit/faas-netes:0.13.2
      - ghcr.io/openfaas/gateway:0.27.0
      - ghcr.io/openfaas/queue-worker:0.14.0
      - prom/prometheus:v2.46.0
      - prom/alertmanager:v0.25.0
      - nats-streaming:0.25.5
      - fcarp10/hello-world
      - fcarp10/fib-go
      - fcarp10/fib-kn
  tasks:
    - ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/registry/registry_deploy.yml"