- name: Hello-world test
  hosts: testers
  vars: 
    repetitions: 1
  tasks:

    - name: Run deployment workflow
      ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment_workflow/workflow_example1.yml"
      with_sequence: count={{ repetitions }}


