- name: OpenFaaS helloworld playbook
  hosts: testers
  vars:
    nebula: 
      nebula_version: 1.5.2
      nebula_address: lighthouse
      nebula_port: 4242
    k3s: 
      k3s_version: v1.23.6+k3s1
      k3s_port: 6443
    openfaas:
      openfaas_version: 14.0.5
      openfaas_port: 31112
      openfaas_namespace: openfaas-fn
      openfaas_functions: hello-world
    registry:
      reg_user: 
      reg_ip: 
      reg_port: 
      reg_dname: 
    netem:
      - name: qos-empty
        intra: 
          delay: 0
          variance: 0
          loss: 0
        tm:   
          delay: 0   
          variance: 0    
          loss: 0  
      - name: qos-tester
        intra: 
          delay: 0
          variance: 0
          loss: 0
        tm:   
          delay: 12.5      
          variance: 2.5   
          loss: 0.2
      - name: qos-intra-tester
        intra: 
          delay: 1.25
          variance: 0.25
          loss: 0.02
        tm: 
          delay: 1.25
          variance: 0.25
          loss: 0.02
      
  tasks:

    - name: Initialize benchmark
      ansible.builtin.include_tasks: "{{ playbook_dir }}/benchmark/init.yml"
    
    - name: Run OpenFaas helloworld test
      ansible.builtin.include_tasks: "{{ playbook_dir }}/benchmark/openfaas/helloworld/helloworld_jmeter.yml"
      with_items:
        - "{{ netem }}"



