- name: Deploy local container registry
  hosts: testers
  vars:
    reg_user: ubuntu
    reg_ip: 192.168.1.247
    reg_port: 5000
    reg_dname: local-registry
    container_images:
      - ghcr.io/openfaas/faas-netes:0.13.2
      - nats-streaming:0.22.0
      - ghcr.io/openfaas/queue-worker:0.12.2
      - prom/prometheus:v2.11.0
      - directxman12/k8s-prometheus-adapter:v0.8.4
      - ghcr.io/openfaas/basic-auth:0.21.1
      - fcarp10/hello-world
      - fcarp10/fib-go
  tasks:
    - ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/registry/registry_deploy.yml"