- name: Mosquitto helloworld playbook
  hosts: testers
  vars:
    num_threads: [1, 10]
    nebula: 
      nebula_version: 1.5.2
      nebula_address: lighthouse
      nebula_port: 4242
    k3s: 
      k3s_version: v1.23.6+k3s1
      k3s_port: 6443
    registry:
      reg_user: 
      reg_ip: 
      reg_port: 
      reg_dname:
    mosquitto:
      mosquitto_version: 1.6.15
      mosquitto_port: 31883
      max_replicas: 5
    netem:
      - name: qos-empty
        intra: 
          delay: 0
          variance: 0
          loss: 0
        tm:   
          delay: 0   
          variance: 0    
          loss: 0  
      - name: qos-tester
        intra: 
          delay: 0
          variance: 0
          loss: 0
        tm:   
          delay: 12.5      
          variance: 2.5   
          loss: 0.2
      - name: qos-intra-tester
        intra: 
          delay: 1.25
          variance: 0.25
          loss: 0.02
        tm: 
          delay: 1.25
          variance: 0.25
          loss: 0.02
      
  tasks:

    - name: Start benchmark
      ansible.builtin.include_tasks: "{{ playbook_dir }}/benchmark/start.yml"

    - name: Run Mosquitto helloworld test
      ansible.builtin.include_tasks: "{{ playbook_dir }}/benchmark/mosquitto/helloworld/helloworld_mqtt-stresser.yml"
      vars:
        - item: "{{ pb_item.0 }}"
      loop: "{{ netem |  product(num_threads)  | list }}"
      loop_control:
        loop_var: pb_item

    - name: Stop benchmark
      ansible.builtin.include_tasks: "{{ playbook_dir }}/benchmark/stop.yml"
