- name: OpenFaaS helloworld playbook
  hosts: testers
  vars:
    num_workers: 2
    vagrant:
      vm_cpu: 2
      vm_mem: 4096
      vm_image: "generic/ubuntu2004"
    nebula: 
      nebula_version: 1.5.2
      nebula_address: lighthouse
      nebula_port: 4242
    k3s: 
      k3s_version: v1.23.6+k3s1
      k3s_port: 6443
    openfaas:
      openfaas_version: 10.0.8
      openfaas_port: 31112
      openfaas_namespace: openfaas-fn
      openfaas_functions: hello-world
    registry:
      reg_user: 
      reg_ip: 
      reg_port: 
      reg_dname: 
    netem:
      - name: qos-empty
        delay_intra: 0    
        variance_intra: 0 
        loss_intra: 0     
        delay_tm: 0       
        variance_tm: 0    
        loss_tm: 0  
      - name: qos-tester
        delay_intra: 0
        variance_intra: 0
        loss_intra: 0
        delay_tm: 12.5
        variance_tm: 2.5
        loss_tm: 0.2
      - name: qos-intra-tester
        delay_intra: 1.25
        variance_intra: 0.25
        loss_intra: 0.02 
        delay_tm: 1.25  
        variance_tm: 0.25 
        loss_tm: 0.02
      
  tasks:
    - name: Set global vars
      ansible.builtin.set_fact:
        foldername: "{{ lookup('pipe', 'date +%Y-%-m-%-d_%H-%M-%S') }}"
        filesuffix: "2rpi"
    - name: Run deployment workflow
      ansible.builtin.include_tasks: "{{ playbook_dir }}/workflow/openfaas/helloworld.yml"
      with_items:
        - "{{ netem }}"


