- hosts: testers
  vars:
    num_workers: 1
    nebula: 
      nebula_version: 1.5.2
      nebula_address: lighthouse
      nebula_port: 4242
    k3s: 
      k3s_version: v1.27.3+k3s1
      k3s_port: 6443
    knative:
      version: v1.10.0
      port: 80
      functions: fib-kn
    registry:
      reg_user:
      reg_ip: 
      reg_port:
      reg_dname:
    netem:
      - name: qos-empty
        intra: 
          delay: 0
          variance: 0
          loss: 0
        tm:   
          delay: 0   
          variance: 0    
          loss: 0  
      - name: qos-tester
        intra: 
          delay: 0
          variance: 0
          loss: 0
        tm:   
          delay: 12.5      
          variance: 2.5   
          loss: 0.2
      - name: qos-intra-tester
        intra: 
          delay: 1.25
          variance: 0.25
          loss: 0.02
        tm: 
          delay: 1.25
          variance: 0.25
          loss: 0.02
      
  tasks:

    - name: Set results directory
      ansible.builtin.set_fact:
        foldername: "{{ lookup('pipe', 'date +%Y-%-m-%-d_%H-%M-%S') }}"
    
    - name: Run Knative helloworld test
      ansible.builtin.include_tasks: "{{ playbook_dir }}/benchmark/knative/helloworld/helloworld_jmeter.yml"
      with_items:
        - "{{ netem }}"



