- hosts: testers
  vars:
    nebula: 
      nebula_version: 1.5.2
      nebula_address: lighthouse
      nebula_port: 4242
    k3s: 
      k3s_version: v1.27.3+k3s1
      k3s_port: 6443
    knative:
      version: v1.10.0
      port: 80
      functions: 
        - hello-world
    registry:
      reg_user:
      reg_ip: 
      reg_port:
      reg_dname:
    netem:
      - name: qos-empty
        intra: 
          delay: 0
          variance: 0
          loss: 0
        tm:   
          delay: 0   
          variance: 0    
          loss: 0  
      - name: qos-tester
        intra: 
          delay: 0
          variance: 0
          loss: 0
        tm:   
          delay: 12.5      
          variance: 2.5   
          loss: 0.2
      - name: qos-intra-tester
        intra: 
          delay: 1.25
          variance: 0.25
          loss: 0.02
        tm: 
          delay: 1.25
          variance: 0.25
          loss: 0.02
      
  tasks:

    - name: Initialize benchmark
      ansible.builtin.include_tasks: "{{ playbook_dir }}/benchmark/init.yml"
         
    - name: Run Knative helloworld test
      ansible.builtin.include_tasks: "{{ playbook_dir }}/benchmark/knative/helloworld/helloworld_jmeter.yml"
      vars:
        - item: "{{ pb_item.0 }}"
        - qos_item: "{{ pb_item.0.name }}"
        - functions_item: "{{ pb_item.1 }}"
        - num_iterations: 100
        - load: 1
      loop: "{{ netem |  product(knative.functions)  | list }}"
      loop_control:
        loop_var: pb_item



