machines:
  hosts:
    machine01:
      ansible_host: 192.168.1.20
      ansible_user: ubuntu
      interface: nebula
      arch: arm64
      headnode: true
      
    machine02:
      ansible_host: 192.168.1.21
      ansible_user: ubuntu
      interface: nebula
      arch: arm64

    machine03:
      ansible_host: 192.168.1.22
      ansible_user: ubuntu
      interface: nebula
      arch: arm64

testers:
  hosts:
    tester01:
      arch: amd64
      ansible_host: localhost
      ansible_user: user
      interface: enp6s0
      address_benchmark: 192.168.1.20
      num_workers: 2
      vagrant:
        vm_cpu: 2
        vm_mem: 4096
        vm_image: "generic/ubuntu2004"
      nebula: 
        nebula_version: 1.5.2
        nebula_address: lighthouse
        nebula_port: 4242
      k3s: 
        k3s_version: v1.23.6+k3s1
        k3s_port: 6443
      k6:
        xk6_verison: 0.9.1
      openfaas:
        openfaas_version: 10.0.8
        openfaas_port: 31112
        openfaas_namespace: openfaas-fn
        openfaas_functions: hello-world
