machines:
  hosts:
    machine01:
      ansible_host: 192.168.1.247
      ansible_user: ubuntu
      interface: enp10s0
      arch: amd64
      headnode: true
      
    machine02:
      ansible_host: 192.168.1.35
      ansible_user: ubuntu
      interface: enx00e04c304b52
      arch: amd64
    
    machine03:
      ansible_host: 192.168.1.83
      ansible_user: ubuntu
      interface: eth0
      arch: arm64

testers:
  hosts:
    tester01:
      ansible_host: localhost
      ansible_user: vegeta
      interface: enp4s0
      arch: amd64
      address_benchmark: 192.168.1.247
        
