machines:
  hosts:
    machine01:
      ansible_host: 192.168.1.247
      ansible_user: ubuntu
      interface: enp10s0
      arch: amd64
      
    machine02:
      ansible_host: 192.168.1.35
      ansible_user: ubuntu
      interface: enx00e04c304b52
      arch: amd64

    machine03:
      ansible_host: notelab1.icos-project.eu
      ansible_user: ubuntu
      interface: eth0
      arch: amd64
      headnode: true

testers:
  hosts:
    tester01:
      ansible_host: localhost
      ansible_user: vegeta
      interface: enp4s0
      address_benchmark: notelab1.icos-project.eu
      num_workers: 2
      vagrant:
        vm_cpu: 2
        vm_mem: 4096
        vm_image: "generic/ubuntu2004"
      nebula: 
        nebula_version: 1.5.2
        nebula_address: lighthouse
        nebula_port: 4242
      k3s: 
        k3s_version: v1.23.6+k3s1
        k3s_port: 6443
      openfaas:
        openfaas_version: 10.0.8
        openfaas_port: 31112
        openfaas_namespace: openfaas-fn
        openfaas_functions: hello-world
      netem:
        delay_intra: 50 
        variance_intra: 2
        loss_intra: 1
        delay_tm: 50
        variance_tm: 0
        loss_tm: 0
