machines:
  hosts:
    machine01:
      ansible_host: 192.168.1.3
      ansible_user: ubuntu
      interface: eth0
      arch: arm64
      headnode: true
      
    machine02:
      ansible_host: 192.168.1.83
      ansible_user: ubuntu
      interface: eth0
      arch: arm64

testers:
  hosts:
    tester01:
      ansible_host: localhost
      ansible_user: vegeta
      interface: enp4s0
      address_benchmark: 192.168.1.3
      num_workers: 1
      nebula: 
        nebula_version: 1.5.2
        nebula_address: lighthouse
        nebula_port: 4242
      k3s: 
        k3s_version: v1.23.6+k3s1
        k3s_port: 6443
      openfaas:
        openfaas_version: 10.0.8
        openfaas_port: 31112
        openfaas_namespace: openfaas-fn
        openfaas_functions: hello-world
      netem:
        delay_intra: 50 
        variance_intra: 2
        loss_intra: 1
        delay_tm: 50
        variance_tm: 0
        loss_tm: 0
