apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fib-kn
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/window: "20s"
        autoscaling.knative.dev/panic-window-percentage: "25.0"
        autoscaling.knative.dev/panic-threshold-percentage: "120.0"
        # max-scale-up-rate: "500.0"
    spec:
      # containerConcurrency: 50
      containers:
        - image: fcarp10/fib-kn:latest
          ports:
            - containerPort: 8080
