- name: Initialize BenchFaster
  ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/core/start.yml"

- name: Install Mosquitto
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/mosquitto/mosquitto_install.yml"

- name: Run MQTT helloworld test
  ansible.builtin.shell: |
    docker run --rm inovex/mqtt-stresser \
      -broker tcp://{{ address_benchmark }}:{{ mosquitto.mosquitto_port }} \
      -num-clients {{ pb_item.1 }} \
      -num-messages 150 \
      -rampup-delay 1s \
      -rampup-size 10 \
      -global-timeout 180s \
      -timeout 20s \
      -no-progress \
    >> {{ results_path.path }}/helloworld-mqtt_W-{{ groups['workers'] | length }}_Q-{{ pb_item.0.name }}_T-{{ pb_item.1 }}.txt

- name: Copy results to control node
  synchronize:
    src: "{{ results_path.path }}"
    dest: "{{ playbook_dir }}/_results/"
    mode: pull

- name: Delete BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}deployment/core/stop.yml"
