- name: Initialize BenchFaster
  ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/init.yml"

- name: Install Mosquitto
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/mosquitto/mosquitto_install.yml"

- name: Run MQTT helloworld test
  ansible.builtin.shell: |
    docker run --rm inovex/mqtt-stresser \
      -broker tcp://{{ address_benchmark }}:{{ mosquitto.mosquitto_port }} \
      -num-clients {{ pb_item.1 }} \
      -num-messages 150 \
      -rampup-delay 1s \
      -rampup-size 10 \
      -global-timeout 180s \
      -timeout 20s \
      -no-progress \
    >> {{ results_path.path }}/helloworld-mqtt_W-{{ num_workers }}_Q-{{ pb_item.0.name }}_T-{{ pb_item.1 }}.txt

- name: Copy results to control node
  ansible.builtin.command: rsync -a "{{ ansible_user }}"@"{{ ansible_host }}":/home/"{{ ansible_user }}"/benchfaster/_results "{{ playbook_dir }}"/
  delegate_to: 127.0.0.1

- name: Delete BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/delete.yml"