- name: Recursively remove nebula certificates directory
  ansible.builtin.file:
    path: "{{ toolkit_dir }}/nebula/config/cert"
    state: absent

- name: Create certificates directory
  ansible.builtin.file:
    path: "{{ toolkit_dir }}/nebula/config/cert"
    state: directory

- name: Generate nebula certificates - lighthouse
  ansible.builtin.shell: |
      nebula-cert ca -name "BenchFaster"
      nebula-cert sign -name "lighthouse" -ip "192.168.50.99/24"
  args:
    chdir: "{{ toolkit_dir }}/nebula/config/cert/"

#TODO: adapt loop control to new inventory
- name: Generate nebula certificates - workers
  ansible.builtin.shell: nebula-cert sign -name "worker{{ i + 1 }}" -ip "192.168.50.10{{ i + 1 }}/24"
  loop: "{{ range(0, num_workers, 1)|list }}"
  loop_control:
    index_var: i
    loop_var: worker_item
  args:
    chdir: "{{ toolkit_dir }}/nebula/config/cert/"
