- name: Start BenchFaster
  ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/core/start.yml"
  
- name: Add local container registry
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/core/registry/registry_add.yml"
  
- name: Install Knative
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/knative/install.yml"

- name: Run benchmark per each num_threads and loads
  ansible.builtin.include_tasks: "{{ playbook_dir }}/benchmark/knative/scalability/sub_item.yml"
  vars:
    - num_threads_item: "{{ sub_item.0 }}"
    - loads_item: "{{ sub_item.1 }}"
  loop: "{{ num_threads |  product(loads)  | list }}"
  loop_control:
    loop_var: sub_item

- name: Stop BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/core/stop.yml"