- name: Initialize BenchFaster
  ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/init.yml"
  
- name: Install Knative
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/knative/install.yml"

- name: Run scalability test with JMeter
  ansible.builtin.shell: |
    jmeter -n -t {{ tests_dir }}/knative/scalability/scalability.jmx \ 
      -Jrequest.ip=fib-kn.default.{{ address_benchmark }}.nip.io \
      -Jrequest.port={{ knative.port }} \
      -Jtest.threads={{ pb_item.1 }} \
      -Jtest.argument={{ pb_item.2 }} \
      -l {{ results_path.path }}/scalability-knative_W-{{ num_workers }}_Q-{{ pb_item.0.name }}_T-{{ pb_item.1 }}_L-{{ pb_item.2 }}.csv

- name: Copy results to control node
  ansible.builtin.command: rsync -a "{{ ansible_user }}"@"{{ ansible_host }}":/home/"{{ ansible_user }}"/benchfaster/_results "{{ playbook_dir }}"/
  delegate_to: 127.0.0.1

- name: Delete BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/delete.yml"