- name: Initialize BenchFaster
  ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/init.yml"
  
- name: Install Knative
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/knative/install.yml"

- name: Run scalability test with JMeter
  ansible.builtin.shell: |
    jmeter -n -t {{ tests_dir }}/knative/scalability/scalability.jmx \ 
      -Jrequest.ip={{ functions_item }}.default.{{ address_benchmark }}.nip.io \
      -Jrequest.port={{ knative.port }} \
      -Jtest.threads={{ num_threads_item }} \
      -Jtest.argument={{ loads_item }} \
      -l {{ results_path.path }}/scalability-{{ functions_item }}_W-{{ num_workers }}_Q-{{ qos_item }}_T-{{ num_threads_item }}_L-{{ loads_item }}.csv

- name: Copy results to control node
  ansible.builtin.command: rsync -a "{{ ansible_user }}"@"{{ ansible_host }}":/home/"{{ ansible_user }}"/benchfaster/_results "{{ playbook_dir }}"/
  delegate_to: 127.0.0.1

- name: Delete BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/delete.yml"