- name: Recursively remove nebula certificates directory
  ansible.builtin.file:
    path: "{{ toolkit_dir }}/core/nebula/config/cert"
    state: absent

- name: Create certificates directory
  ansible.builtin.file:
    path: "{{ toolkit_dir }}/core/nebula/config/cert"
    state: directory

- name: Generate nebula certificates - lighthouse
  ansible.builtin.shell: |
      nebula-cert ca -name "BenchFaster"
      nebula-cert sign -name "lighthouse" -ip "192.168.50.99/24"
  args:
    chdir: "{{ toolkit_dir }}/core/nebula/config/cert/"

- name: Generate nebula certificates - workers
  ansible.builtin.shell: nebula-cert sign -name "{{ hostvars[worker_item].inventory_hostname }}" -ip "192.168.50.10{{ i + 1 }}/24"
  loop: "{{ groups['workers'] }}"
  loop_control:
    index_var: i
    loop_var: worker_item
  args:
    chdir: "{{ toolkit_dir }}/core/nebula/config/cert/"
