- name: Install OpenFaas on headnode
  ansible.builtin.shell: |
    ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} \
      "benchfaster/deployment/openfaas/openfaas_install.sh \
      machine \
      {{ openfaas.openfaas_port }} \
      {{ openfaas.openfaas_version }} \
      {{ openfaas.openfaas_namespace }} \
      {{ openfaas.openfaas_functions }} \
      false \
      {{ registry.reg_dname }} \
      {{ registry.reg_port }}" \
      >> {{ results_path.path }}/logs.txt
