- name: Install OpenFaas on headnode
  ansible.builtin.script: "{{ toolkit_dir }}/openfaas/openfaas_install.sh \
      machine \
      {{ openfaas.openfaas_port }} \
      {{ openfaas.openfaas_version }} \
      {{ openfaas.openfaas_namespace }} \
      {{ openfaas.openfaas_functions }} \
      false \
      {{ registry.reg_dname }} \
      {{ registry.reg_port }}"
  become: yes
  delegate_to: "{{ groups['headnodes'][0] }}"
