---
# tasks file for roles/applications/openfaas
- name: Copy files folder to headnode
  copy:
    src: "files/"
    dest: /tmp/benchfaster/
  delegate_to: "{{ current_host }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: current_host
    
- name: Install OpenFaas
  ansible.builtin.script: "openfaas_install.sh \
      machine \
      {{ openfaas.openfaas_port }} \
      {{ openfaas.openfaas_version }} \
      {{ openfaas.openfaas_namespace }} \
      {{ function.name }} \
      false \
      {{ registry.dname }} \
      {{ registry.port }}"
  become: yes
  delegate_to: "{{ groups['headnodes'][0] }}"