- name: Apply QoS set to host
  ansible.builtin.shell: |
    echo "QoS set {{ item.name }} [host: {{ hostvars[groups.machines[hitem]].ansible_host }}, interface: {{ hostvars[groups.machines[hitem]].interface }}, delay: {{ qos.delay }}ms, variance: {{ qos.variance }}ms, loss: {{ qos.loss }}%]..." >> {{ results_path.path }}/logs.txt
    if [ $(echo "{{ qos.delay }} != 0" | bc -l) -eq 1 ] && [ $(echo "{{ qos.variance }} != 0" | bc -l) -eq 1 ] && [ $(echo "{{ qos.loss }} != 0" | bc -l) -eq 1 ]; then
      ssh -n {{ hostvars[groups.machines[hitem]].ansible_user }}@{{ hostvars[groups.machines[hitem]].ansible_host }} "sudo tc qdisc add dev {{ hostvars[groups.machines[hitem]].interface }} root netem delay {{ qos.delay }}ms {{ qos.variance }}ms distribution normal loss {{ qos.loss }}%" >> {{ results_path.path }}/logs.txt
      echo "Delay, variance and loss added!" >> {{ results_path.path }}/logs.txt
    fi
    if [ $(echo "{{ qos.delay }} != 0" | bc -l) -eq 1 ] && [ $(echo "{{ qos.variance }} != 0" | bc -l) -eq 1 ] && [ $(echo "{{ qos.loss }} != 0" | bc -l) -eq 0 ]; then
      ssh -n {{ hostvars[groups.machines[hitem]].ansible_user }}@{{ hostvars[groups.machines[hitem]].ansible_host }} "sudo tc qdisc add dev {{ hostvars[groups.machines[hitem]].interface }} root netem delay {{ qos.delay }}ms {{ qos.variance }}ms" >> {{ results_path.path }}/logs.txt
      echo "Only delay and variance added!" >> {{ results_path.path }}/logs.txt
    fi
    if [ $(echo "{{ qos.delay }} != 0" | bc -l) -eq 1 ] && [ $(echo "{{ qos.variance }} != 0" | bc -l) -eq 0 ] && [ $(echo "{{ qos.loss }} != 0" | bc -l) -eq 0 ]; then
      ssh -n {{ hostvars[groups.machines[hitem]].ansible_user }}@{{ hostvars[groups.machines[hitem]].ansible_host }} "sudo tc qdisc add dev {{ hostvars[groups.machines[hitem]].interface }} root netem delay {{ qos.delay }}ms" >> {{ results_path.path }}/logs.txt
      echo "Only delay added!" >> {{ results_path.path }}/logs.txt
    else
      echo "No QoS to apply" >> {{ results_path.path }}/logs.txt
    fi