- name: Delete QoS set "{{ item.name }}" (intra)
  ansible.builtin.shell: |
    echo "Deleting QoS (intra) [interface: {{ hostvars[machine_item].interface }}]..."
    tc qdisc delete dev "{{ hostvars[machine_item].interface }}" root
  become: yes
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: machine_item
  ignore_errors: True

- name: Delete QoS set "{{ item.name }}" (intra)
  ansible.builtin.shell: |
    echo "Deleting QoS (intra) [interface: {{ hostvars[machine_item].interface }}]..."
    tc qdisc delete dev "{{ hostvars[machine_item].interface }}" root
  become: yes
  loop: "{{ groups['workers'] }}"
  loop_control:
    loop_var: machine_item
  ignore_errors: True

- name: Delete QoS set "{{ item.name }}" (testers)
  ansible.builtin.shell: |
    echo "Deleting QoS (testers) [interface: {{ hostvars[tester_item].interface }}]..."
    tc qdisc delete dev "{{ hostvars[tester_item].interface }}" root
  become: yes
  loop: "{{ groups['workers'] }}"
  loop_control:
    loop_var: tester_item
  ignore_errors: True
