- name: Install OpenFaas on headnode
  ansible.builtin.shell: |
    ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} \
      "/home/{{ headnode.ansible_user }}/benchfaster/deployment_toolkit/openfaas/openfaas_install.sh \
      machine \
      {{ openfaas.openfaas_port }} \
      {{ openfaas.openfaas_version }} \
      {{ openfaas.openfaas_namespace }} \
      {{ openfaas.openfaas_functions }}" \
      >> {{ results_path.path }}/logs.txt
