- name: Start BenchFaster
  ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/core/start.yml"
  
- name: Install OpenFaas
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/openfaas/openfaas_install.yml"

- name: Run helloworld test with JMeter
  ansible.builtin.shell: |
    jmeter -n -t {{ tests_dir }}/openfaas/helloworld/helloworld.jmx \
      -Jrequest.ip={{ address_benchmark }} \
      -Jrequest.port={{ openfaas.openfaas_port }} \
      -Jtest.iterations=100 \
      -l {{ results_path.path }}/helloworld-jmeter_openfaas_W-{{ groups['workers'] | length }}_Q-{{ item.name }}.csv

- name: Stop BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/core/stop.yml"
