- name: Run helloworld test with K6
  ansible.builtin.shell: |
    k6 run {{ tests_dir }}/openfaas/helloworld/helloworld.js \
      -e host={{ address_benchmark }} \
      -e port={{ openfaas.openfaas_port }} \
      --iterations 100 \
      -o csv={{ results_path.path }}/helloworld-k6_openfaas_{{ filesuffix }}_{{ item.name }}.csv
