- name: Start BenchFaster
  ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/core/start.yml"

- name: Install OpenFaas
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/openfaas/openfaas_install.yml"
  
- name: Run helloworld test with K6
  ansible.builtin.shell: |
    k6 run {{ tests_dir }}/openfaas/helloworld/helloworld.js \
      -e host={{ address_benchmark }} \
      -e port={{ openfaas.openfaas_port }} \
      --iterations 100 \
      -o csv={{ results_path.path }}/helloworld-k6_openfaas_{{ groups['workers'] | length }}_{{ item.name }}.csv

- name: Stop BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/core/stop.yml"