- name: Run helloworld test with K6
  ansible.builtin.shell: |
    k6 run {{ tests_dir }}/helloworld/helloworld.js \
      -e HOST={{ address_benchmark }} \
      -e PORT={{ openfaas.openfaas_port }} \
      --iterations 100 \
      -o csv={{ results_path.path }}/results_k6.csv