- name: Run helloworld test with JMeter
  ansible.builtin.shell: |
    jmeter -n -t {{ tests_dir }}/helloworld/helloworld.jmx \ 
      -Jrequest.ip={{ address_benchmark }} \
      -Jrequest.port={{ openfaas.openfaas_port }} \
      -Jtest.iterations=100 \
      -l {{ results_path.path }}/helloworld-jmeter_openfaas_null_{{ filesuffix }}_{{ item.name }}.csv
