- name: Generate Nebula certificates
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/nebula/nebula_certs.yml"

- name: Register headnode
  ansible.builtin.set_fact:
    headnode: "{{ hostvars[groups.machines[i]] }}"
  loop: "{{ range(0, groups.machines|length, 1)|list }}"
  loop_control:
    index_var: i
    loop_var: headnode_item
  when: hostvars[groups.machines[headnode_item]].headnode is defined

- name: Copy BenchFaster to machines
  ansible.builtin.shell: |
    ssh -n {{ hostvars[groups.machines[machine_item]].ansible_user }}@{{ hostvars[groups.machines[machine_item]].ansible_host }} "find ./benchfaster -mindepth 1 ! -regex '^./benchfaster/_results\(/.*\)?' -delete"
    rsync -e 'ssh -ax' -av --exclude _results/ --exclude _plots/ {{ playbook_dir }} {{ hostvars[groups.machines[machine_item]].ansible_user }}@{{ hostvars[groups.machines[machine_item]].ansible_host }}:/home/{{ hostvars[groups.machines[machine_item]].ansible_user }}
  loop: "{{ range(0, groups.machines|length, 1)|list }}"
  loop_control:
    loop_var: machine_item
  delegate_to: 127.0.0.1

- name: Delete QoS from all nodes
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/qos_delete.yml"
  when: hvm is not defined

- name: Deploy Nebula network
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/nebula/nebula_network.yml"
  when: hvm is not defined

- name: Deploy K3s cluster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/k3s/k3s_cluster.yml"
  when: hvm is not defined

- name: Apply QoS to all nodes
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/qos.yml"
  when: hvm is not defined
