- name: Register headnode
  ansible.builtin.set_fact:
    headnode: "{{ hostvars[groups.machines[i]] }}"
  loop: "{{ range(0, groups.machines|length, 1)|list }}"
  loop_control:
    index_var: i
    loop_var: headnode_item
  when: hostvars[groups.machines[headnode_item]].headnode is defined

- name: Create results directory
  ansible.builtin.file:
    path: "{{ playbook_dir }}/_results/{{ foldername }}"
    state: directory
  register: results_path

- name: Copy BenchFaster to machines
  ansible.builtin.shell: |
    ssh -n {{ hostvars[groups.machines[machine_item]].ansible_user }}@{{ hostvars[groups.machines[machine_item]].ansible_host }} "rm -rf benchfaster"
    echo "Copying BenchFaster to {{ hostvars[groups.machines[machine_item]] }} ..." >> {{ results_path.path }}/logs.txt
    rsync -e 'ssh -ax' -av --exclude _results/ --exclude _plots/ {{ playbook_dir }} {{ hostvars[groups.machines[machine_item]].ansible_user }}@{{ hostvars[groups.machines[machine_item]].ansible_host }}:/home/{{ hostvars[groups.machines[machine_item]].ansible_user }}
  loop: "{{ range(0, groups.machines|length, 1)|list }}"
  loop_control:
    loop_var: machine_item
