- ansible.builtin.set_fact:
    netem: "{{ network.intra }}"

- name: Apply netem set "{{ netem.name }}" (Machines)
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/netem_add.yml"
  args:
    apply:
      delegate_to: "{{ hitem }}"
  loop: "{{ groups['workers'] }}"
  loop_control:
    loop_var: hitem

- name: Apply netem set "{{ netem.name }}" (Headnode)
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/netem_add.yml"
  args:
    apply:
      delegate_to: "{{ hitem }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: hitem

- ansible.builtin.set_fact:
    netem: "{{ network.tm }}"

- name: Apply netem set "{{ netem.name }}" (Testers)
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/netem_add.yml"
  args:
    apply:
      delegate_to: "{{ hitem }}"
  loop: "{{ groups['testers'] }}"
  loop_control:
    loop_var: hitem
