- ansible.builtin.include_role:
    name: "{{ role_item }}"
  with_items:
    - benchfaster/start
    - applications/knative/install
    - applications/knative/function-add
    - benchmark-tools/{{ benchmark_tool }}
    - benchfaster/stop
  loop_control:
    loop_var: role_item