- name: Apply QoS set to host
  ansible.builtin.shell: |
    echo "QoS set {{ item.name }} [host: {{ hitem }}, interface: {{ hostvars[hitem].interface }}, delay: {{ qos.delay }}ms, variance: {{ qos.variance }}ms, loss: {{ qos.loss }}%]..."
    if [ $(echo "{{ qos.delay }} != 0" | bc -l) -eq 1 ] && [ $(echo "{{ qos.variance }} != 0" | bc -l) -eq 1 ] && [ $(echo "{{ qos.loss }} != 0" | bc -l) -eq 1 ]; then
      tc qdisc add dev {{ hostvars[hitem].interface }} root netem delay {{ qos.delay }}ms {{ qos.variance }}ms distribution normal loss {{ qos.loss }}% 
      echo "Delay, variance and loss added!" 
    fi
    if [ $(echo "{{ qos.delay }} != 0" | bc -l) -eq 1 ] && [ $(echo "{{ qos.variance }} != 0" | bc -l) -eq 1 ] && [ $(echo "{{ qos.loss }} != 0" | bc -l) -eq 0 ]; then
      tc qdisc add dev {{ hostvars[hitem].interface }} root netem delay {{ qos.delay }}ms {{ qos.variance }}ms
      echo "Only delay and variance added!" >> {{ results_path.path }}/logs.txt
    fi
    if [ $(echo "{{ qos.delay }} != 0" | bc -l) -eq 1 ] && [ $(echo "{{ qos.variance }} != 0" | bc -l) -eq 0 ] && [ $(echo "{{ qos.loss }} != 0" | bc -l) -eq 0 ]; then
      tc qdisc add dev {{ hostvars[hitem].interface }} root netem delay {{ qos.delay }}ms
      echo "Only delay added!"
    else
      echo "No QoS to apply"
    fi
  become: yes
