- name: Run scalability test with JMeter
  ansible.builtin.shell: |
    jmeter -n -t {{ tests_dir }}/scalability/scalability.jmx \ 
      -Jrequest.ip={{ address_benchmark }} \
      -Jrequest.port={{ openfaas.openfaas_port }} \
      -Jtest.argument=1 \
      -Jtest.threads=500 \
      -l {{ results_path.path }}/scalability_openfaas_{{ filesuffix }}_{{ item.name }}.csv
