- name: Set toolkit directory
  ansible.builtin.set_fact:
    toolkit_dir: "{{ playbook_dir }}/deployment"
    tests_dir: "{{ playbook_dir }}/benchmark"

- name: Generate Nebula certificates
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/nebula/nebula_certs.yml"

- name: Initialize BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/init.yml"

- name: Deploy Nebula network
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/nebula/nebula_network.yml"
  when: hvm is not defined

- name: Deploy K3s cluster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/k3s/k3s_cluster.yml"
  when: hvm is not defined
  
- name: Install Mosquitto
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/mosquitto/mosquitto_install.yml"
  when: hvm is not defined

- name: Delete QoS from all nodes
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/qos_delete.yml"
  when: hvm is not defined

- name: Apply QoS to all nodes
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/qos.yml"
  when: hvm is not defined

- name: Run helloworld test with JMeter
  ansible.builtin.include_tasks: "{{ tests_dir }}/mqtt/helloworld/helloworld_jmeter.yml"

- name: Delete QoS from all nodes
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/qos_delete.yml"
  when: hvm is not defined
  
