---
# tasks file for roles/applications/mosquitto
- name: Copy files folder to headnode
  copy:
    src: "files/"
    dest: /tmp/benchfaster/
  delegate_to: "{{ current_host }}"
  loop: "{{ groups['headnodes'] }}"
  loop_control:
    loop_var: current_host
    
- name: Install Mosquitto
  ansible.builtin.script: "mosquitto_install.sh {{ mosquitto.max_replicas }}"
  delegate_to: "{{ groups['headnodes'][0] }}"