- name: Start BenchFaster
  ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/core/start.yml"
  
- name: Install Knative
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/knative/install.yml"

- name: Install Knative functions
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/knative/functions/install.yml"

- name: Copy benchmark folder to tester node
  ansible.builtin.synchronize:
    src: "{{ playbook_dir }}/benchmark/knative/helloworld"
    dest: /tmp/benchfaster/
    mode: push

- name: Run helloworld test with JMeter
  ansible.builtin.shell: |
    jmeter -n -t /tmp/benchfaster/helloworld/helloworld.jmx \ 
      -Jrequest.ip={{ functions_item }}.default.{{ address_benchmark }}.nip.io \
      -Jrequest.port={{ knative.port }} \
      -Jtest.iterations={{ num_iterations }} \
      -Jtest.argument={{ load }} \
      -l {{ results_path.path }}/scalability-{{ functions_item }}_W-{{ groups['workers'] | length }}_Q-{{ item.name }}.csv

- name: Stop BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/core/stop.yml"