---
# tasks file for roles/applications/knative/function-delete
    #sudo -E kubectl delete service.serving.knative.dev {{ function.name }}
- name: Delete Knative function
  ansible.builtin.shell: |
    sudo -E kubectl delete -f /tmp/benchfaster/{{ func_item }}.yaml
    sudo -E kubectl wait --for=delete pod --all -n default --timeout=10m
  become: yes
  with_items:
    - "{{ functions }}"
  loop_control:
    loop_var: func_item
  delegate_to: "{{ groups['headnodes'][0] }}"
