apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  selector:
    matchLabels:
        run: rabbitmq
  replicas: 1
  template:
    metadata:
        labels:
          run: rabbitmq
    spec:
        containers:
        - name: rabbitmq
          image: rabbitmq:3.11
          ports:
          - containerPort: 5672
          - containerPort: 1883
          volumeMounts:
          - name: plugins
            mountPath: /etc/rabbitmq/enabled_plugins
            subPath: enabled_plugins
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
        volumes:
        - name: plugins
          configMap:
            name: enabledplugins
