- name: Install machine requirements
  hosts: machines
  tasks:

    - name: Install requirements (Ubuntu 22.04)
      ansible.builtin.apt:
        pkg:
        - curl
        - jq
        - wget
        update_cache: no
        state: present
      become: true
      when: ansible_facts['distribution']=="Ubuntu"

    - name: Install requirements (Archlinux) 
      community.general.pacman:
        name:
          - curl
          - jq
          - wget
        update_cache: no
        state: present
      become: true
      when: ansible_facts['distribution']=="Archlinux"
