- name: Install Docker
  hosts: testers
  tasks:
    - name: Install Docker (Archlinux)
      ansible.builtin.command: paru -S --noconfirm --needed {{ item }}
      with_items:
        - docker
      when: ansible_facts['distribution']=="Archlinux"

    - name: Docker post-installation steps
      ansible.builtin.shell: |
        sudo usermod -aG docker $USER
        newgrp docker
        sudo systemctl enable --now docker.service