- name: Install Hey
  hosts: testers
  tasks:
    - name: Install Hey (Ubuntu 22.04)
      ansible.builtin.apt:
        pkg:
          - hey
        state: present
      become: true
      when: ansible_facts['distribution']=="Ubuntu"

    - name: Install Hey (Archlinux)
      ansible.builtin.command: paru -S --noconfirm --needed {{ item }}
      with_items:
        - hey
      when: ansible_facts['distribution']=="Archlinux"
