- name: Install k6
  hosts: testers
  tasks:
        
    - name: Add k6 repos (Ubuntu 22.04)
      ansible.builtin.shell: |
        sudo gpg -k
        sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
        echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt-get update
      become: true
      when: ansible_facts['distribution']=="Ubuntu"

    - name: Install k6 and go (Ubuntu 22.04)
      ansible.builtin.apt:
        pkg:
          - k6
          - golang-1.18-go
        state: present
      become: true
      when: ansible_facts['distribution']=="Ubuntu"

    - name: Install k6 and go (Archlinux)
      ansible.builtin.command: paru -S --noconfirm --needed {{ item }}
      with_items:
        - k6-bin
        - go
      when: ansible_facts['distribution']=="Archlinux"

    #TODO: this does not work yet, throws no error but xk6 is unusable
    - name: Build xk6
      ansible.builtin.command: go install {{ item }}
      with_items:
        - go.k6.io/xk6/cmd/xk6@latest
      environment:
        GOPATH: /tmp/go
        GO111MODULE: auto

    - name: Install Go binaries
      ansible.builtin.shell: |
        cp /tmp/go/bin/* /usr/local/bin
      become: true
