- name: Install tester requirements
  hosts: testers
  tasks:

    - name: Install requirements (only Ubuntu 22.04)
      ansible.builtin.apt:
        pkg:
          - jmeter
        state: present
      become: true
      when: ansible_facts['distribution']=="Ubuntu"

    # - name: Install requirements (only Ubuntu 22.04) # Install Nebula on Ubuntu 22.04 (TO-DO)
    #   ansible.builtin.shell: |
    #     sudo wget ...
    #   become: true
    #   when: ansible_facts['distribution']=="Ubuntu"

    - name: Install requirements (only Archlinux, with paru) # nebula only to generate certs
      community.general.pacman:
        pkg:
          - jmeter
          - nebula
        state: present
        executable: paru
      become: true
      when: ansible_facts['distribution']=="Archlinux"

    - name: Recursively remove nebula certificates directory
      ansible.builtin.file:
        path: "{{ toolkit_dir }}/nebula/config/cert"
        state: absent

    - name: Create certificates directory
      ansible.builtin.file:
        path: "{{ toolkit_dir }}/nebula/config/cert"
        state: directory

    - name: Generate nebula certificates - lighthouse
      ansible.builtin.shell: |
          nebula-cert ca -name "BenchFaster"
          nebula-cert sign -name "lighthouse" -ip "192.168.50.100/24"
      args:
        chdir: "{{ toolkit_dir }}/nebula/config/cert/"

    - name: Generate nebula certificates - workers
      ansible.builtin.shell: nebula-cert sign -name "worker{{ i + 1 }}" -ip "192.168.50.10{{ i + 1 }}/24"
      loop: "{{ range(0, num_machines|int , 1) | list }}"
      loop_control:
        index_var: i
      args:
        chdir: "{{ toolkit_dir }}/nebula/config/cert/"

