- name: Install Docker
  hosts: testers
  tasks:

    - name: Install Docker (Ubuntu 22.04)
      ansible.builtin.apt:
        pkg:
          - docker.io
        state: present
      become: true
      when: ansible_facts['distribution']=="Ubuntu"

    - name: Install Docker (Archlinux)
      ansible.builtin.command: paru -S --noconfirm --needed {{ item }}
      with_items:
        - docker
      when: ansible_facts['distribution']=="Archlinux"

    - name: Docker post-installation steps
      ansible.builtin.shell: |
        sudo usermod -aG docker $USER
        sudo systemctl enable --now docker.service