- name: Install k6
  hosts: testers
  tasks:
    - name: Install requirements (Ubuntu 22.04)
      ansible.builtin.apt:
        pkg:
          - k6
          - golang-1.18-go
        state: present
      become: true
      when: ansible_facts['distribution']=="Ubuntu"

    - name: Install requirements (Archlinux)
      ansible.builtin.command: paru -S --noconfirm --needed {{ item }}
      with_items:
        - k6-bin
        - go
      when: ansible_facts['distribution']=="Archlinux"

    #TODO: this does not work yet, throws no error but xk6 is unusable
    - name: Build xk6
      ansible.builtin.command: go install {{ item }}
      with_items:
        - go.k6.io/xk6/cmd/xk6@latest
      environment:
        GOPATH: /tmp/go
        GO111MODULE: auto

    - name: Install Go binaries
      ansible.builtin.shell: |
        cp /tmp/go/bin/* /usr/local/bin
      become: true
