- name: Install tester requirements
  hosts: testers
  tasks:

    - name: Install requirements (only Ubuntu 22.04)
      ansible.builtin.apt:
        pkg:
          - jmeter
        state: present
      become: true
      when: ansible_facts['distribution']=="Ubuntu"

    # - name: Install requirements (only Ubuntu 22.04) # Install Nebula on Ubuntu 22.04 (TO-DO)
    #   ansible.builtin.shell: |
    #     sudo wget ...
    #   become: true
    #   when: ansible_facts['distribution']=="Ubuntu"

    - name: Install requirements (only Archlinux, with paru) # nebula only to generate certs
      community.general.pacman:
        pkg:
          - jmeter
          - nebula
          - k6-bin
        state: present
        executable: paru
      become: true
      when: ansible_facts['distribution']=="Archlinux"

