apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fib-go
  namespace: functions
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/target: "10"
    spec:
      containerConcurrency: 100
      containers:
        - image: fcarp10/fib-go:latest
          ports:
            - containerPort: 8082
