apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "1"
        autoscaling.knative.dev/initial-scale: "1"
    spec:
      containerConcurrency: 1
      affinity:
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - worker
      containers:
        - image: michalkeit/hello-world:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "2Gi"
              cpu: "2000m"
---
apiVersion: v1
kind: ConfigMap
metadata:
 name: config-autoscaler
 namespace: knative-serving
data:
 enable-scale-to-zero: "false"
