apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
  namespace: functions
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containerConcurrency: 1
      containers:
        - image: fcarp10/hello-world:latest
          ports:
            - containerPort: 80
