apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sleep-fn
  namespace: functions
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containers:
        - image: fcarp10/sleep-fn:latest
          ports:
            - containerPort: 8080
