apiVersion: v1
kind: Service
metadata:
   name: rabbitmq-nodeport
   namespace: rabbitmq
   labels:
      run: rabbitmq
spec:
   selector:
      run: rabbitmq
   type: NodePort
   ports:
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
     nodePort: 30672
   - name: mqtt
     port: 1883
     targetPort: 1883
     nodePort: 31887
     protocol: TCP
