apiVersion: v1
kind: Service
metadata:
   name: mosquitto-nodeport
   namespace: mosquitto
   labels:
      run: mosquitto
spec:
   selector:
      run: mosquitto
   type: NodePort
   ports:
   - name: mqtt
     port: 1883
     targetPort: 1883
     nodePort: 31883
     protocol: TCP
