- name: Start BenchFaster
  ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/core/start.yml"

- name: Install Knative
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/knative/install.yml"

- name: Copy benchmark folder to tester node
  ansible.builtin.synchronize:
    src: "{{ playbook_dir }}/benchmark/knative/sleep"
    dest: /tmp/benchfaster/
    mode: push

- name: Run benchmark per lambda
  ansible.builtin.include_tasks: "{{ playbook_dir }}/benchmark/knative/sleep/sub_item.yml"
  with_sequence: 1-{{ num_lambdas }}
  loop_control:
    loop_var: lambda_item

- name: Stop BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/core/stop.yml"
