- name: Initialize BenchFaster
  ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/init.yml"

- name: Install Knative
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/knative/install.yml"

- name: Run benchmark per lambda
  ansible.builtin.include_tasks: "{{ playbook_dir }}/benchmark/knative/sleep/sub_item.yml"
  with_sequence: 1-{{ num_lambdas }}
  loop_control:
    loop_var: lambda_item

- name: Copy results to control node
  ansible.builtin.command: rsync -a "{{ ansible_user }}"@"{{ ansible_host }}":/home/"{{ ansible_user }}"/benchfaster/_results "{{ playbook_dir }}"/
  delegate_to: 127.0.0.1

- name: Delete BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/delete.yml"
