- name: Initialize BenchFaster
  ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/init.yml"

- name: Install Knative
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/knative/install.yml"

- name: Run benchmark per lambda
  ansible.builtin.include_tasks: "{{ playbook_dir }}/benchmark/knative/sleep/sub_item.yml"
  with_sequence: 1-{{ num_lambdas }}
  loop_control:
    loop_var: lambda_item

- name: Delete BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/delete.yml"
