- name: Install Knative functions
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/knative/fn-install.yml"

- name: Run sleep test with JMeter
  ansible.builtin.shell: |
    jmeter -n -t /tmp/benchfaster/sleep/sleep.jmx \
      -Jrequest.ip={{ functions_item }}.default.{{ address_benchmark }}.nip.io \
      -Jrequest.port={{ knative.port }} \
      -Jtest.pathLoads=/tmp/benchfaster/sleep/_data/{{ data_source }}/{{ test_item }} \
      -Jtest.iterations={{ iterations }} \
      -Jrequest.sleep_time_f1={{ sleep_times.0 }} \
      -Jrequest.sleep_time_f2={{ sleep_times.1 }} \
      -Jrequest.sleep_time_f3={{ sleep_times.2 }} \
      -Jrequest.sleep_time_f4={{ sleep_times.3 }} \
      -Jrequest.sleep_time_f5={{ sleep_times.4 }} \
      -l {{ results_path.path }}/{{ data_source }}-{{ test_item }}_W-{{ groups['workers'] | length }}_Q-{{ item.name }}.csv

- name: Delete Knative functions
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/knative/fn-delete.yml"