- name: Set toolkit directory
  ansible.builtin.set_fact:
    toolkit_dir: "{{ playbook_dir }}/deployment"
    tests_dir: "{{ playbook_dir }}/benchmark"

- name: Generate Nebula certificates
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/nebula/nebula_certs.yml"

- name: Initialize BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/init.yml"

- name: Delete QoS from all nodes
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/qos_delete.yml"
  when: hvm is not defined
  
- name: Deploy Nebula network
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/nebula/nebula_network.yml"
  when: hvm is not defined

- name: Deploy K3s cluster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/k3s/k3s_cluster.yml"
  when: hvm is not defined
  
- name: Install OpenFaas on headnode
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/openfaas/openfaas_install.yml"
  when: hvm is not defined

- name: Delete QoS from all nodes
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/qos_delete.yml"
  when: hvm is not defined

- name: Apply QoS to all nodes
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/qos.yml"
  when: hvm is not defined

- name: Deploy BenchFaster in hypervisor 
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/hvm.yml"
  when: hvm is defined

- name: Run helloworld test with JMeter
  ansible.builtin.include_tasks: "{{ tests_dir }}/openfaas/helloworld/helloworld_jmeter.yml"

- name: Run helloworld test with K6
  ansible.builtin.include_tasks: "{{ tests_dir }}/openfaas/helloworld/helloworld_k6.yml"

- name: Copy results from tester to control node
  ansible.builtin.command: rsync -a "{{ ansible_user }}"@"{{ ansible_host }}":/home/"{{ ansible_user }}"/benchfaster/_results "{{ playbook_dir }}"/
  delegate_to: 127.0.0.1

- name: Delete QoS from all nodes
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/netem/qos_delete.yml"
  when: hvm is not defined
  
