- name: Install Knative
  ansible.builtin.script: "{{ toolkit_dir }}/knative/install.sh \
      machine \
      {{ knative.version }} \
      {{ address_benchmark }} \
      {{ registry.reg_dname }} \
      {{ registry.reg_port }}"
  become: yes
  delegate_to: "{{ groups['headnodes'][0] }}"
