- name: Run scalability test with JMeter
  ansible.builtin.shell: |
    jmeter -n -t {{ tests_dir }}/openfaas/scalability/scalability.jmx \ 
      -Jrequest.ip={{ address_benchmark }} \
      -Jrequest.port={{ openfaas.openfaas_port }} \
      -Jtest.threads={{ pb_item.1 }} \
      -Jtest.argument={{ pb_item.2 }} \
      -l {{ results_path.path }}/scalability-openfaas_W-{{ num_workers }}_Q-{{ pb_item.0.name }}_T-{{ pb_item.1 }}_L-{{ pb_item.2 }}.csv
