- name: Start BenchFaster
  ansible.builtin.include_tasks: "{{ playbook_dir }}/deployment/core/start.yml"

- name: Add local container registry
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/core/registry/registry_add.yml"
  
- name: Install OpenFaas
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/openfaas/openfaas_install.yml"

- name: Run scalability test with JMeter
  ansible.builtin.shell: |
    jmeter -n -t {{ tests_dir }}/openfaas/scalability/scalability.jmx \ 
      -Jrequest.ip={{ address_benchmark }} \
      -Jrequest.port={{ openfaas.openfaas_port }} \
      -Jtest.threads={{ pb_item.1 }} \
      -Jtest.argument={{ pb_item.2 }} \
      -l {{ results_path.path }}/scalability-openfaas_W-{{ groups['workers'] | length }}_Q-{{ pb_item.0.name }}_T-{{ pb_item.1 }}_L-{{ pb_item.2 }}.csv

- name: Stop BenchFaster
  ansible.builtin.include_tasks: "{{ toolkit_dir }}/core/stop.yml"