- name: Set global vars
  ansible.builtin.set_fact:
    reg_port: "{{ hostvars[groups.testers[0]].registry.reg_port }}"
    reg_ip: "{{ hostvars[groups.testers[0]].registry.reg_ip }}"
    reg_dname: "{{ hostvars[groups.testers[0]].registry.reg_dname }}"
    container_images: "{{ hostvars[groups.testers[0]].registry.container_images }}"

- name: Add local container registry to all machines
  ansible.builtin.shell: |
    ssh -n {{ hostvars[groups.machines[machine_item]].ansible_user }}@{{ hostvars[groups.machines[machine_item]].ansible_host }} "sudo sed -i '/{{ reg_dname }}/d' /etc/hosts"
    echo "Adding local container registry {{ reg_dname }}:{{ reg_port }} to {{ hostvars[groups.machines[machine_item]].ansible_host }}" >> {{ results_path.path }}/logs.txt
    ssh -n {{ hostvars[groups.machines[machine_item]].ansible_user }}@{{ hostvars[groups.machines[machine_item]].ansible_host }} "cat << EOF | sudo tee /etc/rancher/k3s/registries.yaml > /dev/null
    mirrors:
      "{{ reg_dname }}:{{ reg_port }}":
        endpoint:
          - "http://{{ reg_dname }}:{{ reg_port }}"
    EOF"
    ssh -n {{ hostvars[groups.machines[machine_item]].ansible_user }}@{{ hostvars[groups.machines[machine_item]].ansible_host }} "echo '{{ reg_ip }} {{ reg_dname }}' | sudo tee -a /etc/hosts"
    ssh -n {{ hostvars[groups.machines[machine_item]].ansible_user }}@{{ hostvars[groups.machines[machine_item]].ansible_host }} "sudo systemctl restart k3s*"
  loop: "{{ range(0, groups.machines|length, 1)|list }}"
  loop_control:
    loop_var: machine_item
