- name: Deploy local container registry
  hosts: testers
  tasks:
    - name: Set global vars
      ansible.builtin.set_fact:
        reg_port: "{{ hostvars[groups.testers[0]].registry.reg_port }}"
        reg_ip: "{{ hostvars[groups.testers[0]].registry.reg_ip }}"
        container_images: "{{ hostvars[groups.testers[0]].registry.container_images }}"

    - name: Remove old local container registry
      ansible.builtin.shell: |
        docker container stop registry && docker container rm -v registry
      ignore_errors: True

    - name: Deploy local container registry
      ansible.builtin.shell: |
        docker run -d -p {{ reg_port }}:5000 --restart=always --name registry registry:2
    
    - name: Pull container images and push to local registry 
      ansible.builtin.shell: |
        docker pull {{ item }} 
        docker tag {{ item }} localhost:{{ reg_port }}/{{ item }}
        docker push localhost:{{ reg_port }}/{{ item }}
      with_items:
        - "{{ container_images }}"
