- name: Set global vars
  ansible.builtin.set_fact:
    reg_port: "{{ hostvars[groups.testers[0]].registry.reg_port }}"
    reg_ip: "{{ hostvars[groups.testers[0]].registry.reg_ip }}"
    container_images: "{{ hostvars[groups.testers[0]].registry.container_images }}"

- name: Add local container registry to K3s
  ansible.builtin.shell: |
    echo "Adding local container registry {{ reg_ip }}:{{ reg_port }} to K3s" >> {{ results_path.path }}/logs.txt
    cat << EOF | sudo tee /etc/rancher/k3s/registries.yaml > /dev/null
    mirrors:
      "{{ reg_ip }}:{{ reg_port }}":
        endpoint:
          - "http://{{ reg_ip }}:{{ reg_port }}"
    EOF
    sudo systemctl restart k3s*
