- name: Deploy local container registry
  hosts: testers
  tasks:
    - name: Register headnode
      ansible.builtin.set_fact:
        headnode: "{{ hostvars[groups.machines[i]] }}"
      loop: "{{ range(0, groups.machines|length, 1)|list }}"
      loop_control:
        index_var: i
        loop_var: headnode_item
      when: hostvars[groups.machines[headnode_item]].headnode is defined

    - name: Set global vars
      ansible.builtin.set_fact:
        reg_port: "{{ hostvars[groups.testers[0]].registry.reg_port }}"
        reg_ip: "{{ hostvars[groups.testers[0]].registry.reg_ip }}"
        reg_dname: "{{ hostvars[groups.testers[0]].registry.reg_dname }}"
        container_images: "{{ hostvars[groups.testers[0]].registry.container_images }}"

    - name: Remove old local container registry
      ansible.builtin.shell: |
        ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} "docker container stop registry && docker container rm -v registry"
        ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} "sudo sed -i '/{{ reg_dname }}/d' /etc/hosts"
        ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} "echo '{{ reg_ip }} {{ reg_dname }}' | sudo tee -a /etc/hosts"
      ignore_errors: True

    - name: Add insecure registry to docker
      ansible.builtin.shell: |
        ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} "sudo rm /etc/docker/daemon.json"
        ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} "sudo mkdir -p /etc/docker"
        ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} "cat << EOF | sudo tee /etc/docker/daemon.json > /dev/null
        {
          \"insecure-registries\": [\"{{ reg_dname }}:{{ reg_port }}\"]
        }
        EOF"
        ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} "sudo systemctl restart docker"

    - name: Deploy local container registry
      ansible.builtin.shell: |
        ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} "docker run -d -p {{ reg_port }}:5000 --restart=always --name registry registry:2"
    
    - name: Pull container images and push to local registry 
      ansible.builtin.shell: |
        ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} "docker pull {{ item }}"
        ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} "docker tag {{ item }} {{ reg_dname }}:{{ reg_port }}/{{ item }}"
        ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} "docker push {{ reg_dname }}:{{ reg_port }}/{{ item }}"
      with_items:
        - "{{ container_images }}"
