- name: Add local container registry to K3s (TO-DO)
  ansible.builtin.shell: |
    echo "Reading config for repo $REPONAME at $REPOIP:$REPOPORT" >> {{ results_path.path }}/logs.txt
    if [[ -n $(cat /etc/hosts | grep ${REPONAME}) ]]; then
      sudo sed -i "/${REPONAME}$/d" /etc/hosts
    fi
    echo "Private container registry defined, applying settings..."
    cat << EOF | sudo tee /etc/rancher/k3s/registries.yaml > /dev/null
    mirrors:
      "${REPONAME}:${REPOPORT}":
        endpoint:
          - "http://${REPONAME}:${REPOPORT}"
    EOF
    echo "${REPOIP} ${REPONAME}" | sudo tee -a /etc/hosts > /dev/null
    sudo systemctl restart k3s*
