- name: Register headnode
  ansible.builtin.set_fact:
    headnode: "{{ hostvars[groups.machines[i]] }}"
  loop: "{{ range(0, groups.machines|length, 1)|list }}"
  loop_control:
    index_var: i
    loop_var: headnode_item
  when: hostvars[groups.machines[headnode_item]].headnode is defined
  
- name: Set global vars
  ansible.builtin.set_fact:
    date: "{{ lookup('pipe', 'date +%-d-%-m-%Y_%H-%M-%S') }}"

- name: Create results directory
  ansible.builtin.file:
    path: "{{ playbook_dir }}/_results/{{ date }}"
    state: directory
  register: results_path

- name: Copy BenchFaster to machines
  ansible.builtin.shell: |
    sh {{ toolkit_dir }}/main.sh \
      --opt copy \
      --address {{ hostvars[groups.machines[machine_item]].ansible_host }} \
      --user {{ hostvars[groups.machines[machine_item]].ansible_user }} \ 
      --workpath /home/{{ hostvars[groups.machines[machine_item]].ansible_user }}/ \ 
      >> {{ results_path.path }}/logs.txt
  loop: "{{ range(0, groups.machines|length, 1)|list }}"
  loop_control:
    loop_var: machine_item