- name: Deploy BenchFaster
  hosts: testers
  tasks:
    
    - name: Copy BenchFaster to all machines
      ansible.builtin.shell: |
        sh {{ toolkit_dir }}/main.sh \
          --opt copy \
          --address {{ hostvars[groups.machines[item]].ansible_host }} \
          --user {{ hostvars[groups.machines[item]].ansible_user }} \ 
          --workpath /home/{{ hostvars[groups.machines[item]].ansible_user }}/ \ 
          >> {{ results_path.path }}/logs.txt
      loop: "{{ range(0, groups.machines|length, 1)|list }}"

    - name: Deploy Nebula network in all nodes
      ansible.builtin.include_tasks: nebula/nebula_network.yml

    - name: Deploy K3s cluster in all nodes
      ansible.builtin.include_tasks: k3s/k3s_cluster.yml
      
    - name: Install OpenFaas on headnode
      ansible.builtin.shell: |
        ssh -n {{ headnode.ansible_user }}@{{ headnode.ansible_host }} \
          "/home/{{ headnode.ansible_user }}/benchfaster/deployment_toolkit/openfaas/openfaas_install.sh \
          machine \
          {{ headnode.openfaas_port }} \
          {{ headnode.openfaas_version }} \
          {{ headnode.openfaas_namespace }} \
          {{ headnode.openfaas_functions }}" \
          >> {{ results_path.path }}/logs.txt
      args:
        executable: /bin/bash






